### ISSUE TITLE
How to use fias gem

### ISSUE THREAD

**Issue by bulychev-ay** [evilmartians/fias#1]
Мне нужно построить отдельный сервис для использования ФИАС.
Но я новичок в Rails, и продвижение идёт медленно.
Выполнил шаги по скачиваннию и импортированию базы, согласно инструкции, удалось это проделать только на версии гема 0.0.1.
Буду благодарен за любую информацию по тому, как все-таки взаимодействовать с базой данных, как создать и настроить сервис. Возможно, есть инструкции более подробные по применению этого гема в работе. Или какой-то другой источник, который поможет мне разобраться со следующими шагами.

**Comment by gzigzigzeo** [comment]
Я не очень понял вашу задачу. На данном этапе гем может сформировать иерархию объектов с полными названиями и так далее. Это описано в примере. Средства, облегчающие поиск - на очереди.

**Comment by bulychev-ay** [comment]
Понятно. Благодарю.
А есть уже хотя бы ориентировочные сроки появления этих средств для облегчения поиска?

**Comment by gzigzigzeo** [comment]
Думаю, через пару дней.

**Comment by bulychev-ay** [comment]
Это отлично!
Подскажите ещё, пожалуйста, планируете ли вы реализовать также механизм автоматического или полуавтоматического обновления БД ФИАС до актуального состояния в рамках вашего гема fias? И если да, то в какие примерно сроки, если они запланированы.

**Comment by gzigzigzeo** [comment]
Мы такой подход как я пилю использовали в живом проекте с несколькими миллионами объектов с привязкой к адресам. Не факт что в вашем случае он будет правильным - но увидите. Обновления пока не будет потому что оно сильно завязано на архитектуру каждого конкретного приложения. При обновлении ФИАС если, например, адресный объект исчезает, сливается или разделяется на несколько объектов - нужно соответствующие действия предпринять с объектами вашего приложения которые к этому адресу привязаны, а это всегда индивидуально. Скорее всего, будет описания подхода и примеры, инструменты может быть какие-то низкоуровневые - но не скоро, сроков пока нет.

**Comment by bulychev-ay** [comment]
У вас почему-то не загружается в БД таблица из файла HSTSTATE.DBF.
Это специально сделано? Я её вручную загрузил - вроде бы нужные данные.

**Comment by gzigzigzeo** [comment]
Нет, не специально конечно же. Видимо, просто пропустил ее при добавлении в списке таблиц. Вы можете сделать пулл-реквест ну или я на неделе обновлю импорт.
