### ISSUE TITLE
WTF..?!

### ISSUE THREAD

**Issue by halt-hammerzeit** [evilmartians/fias#11]
Какого хрена РЕАДМЕ библиотеки для работы с РУССКИМИ (!) адресами написано на АНГЛИЙСКОМ (!!!) языке?!
Это специздание для хипстеров что ли?!..

**Comment by demiazz** [comment]
@halt-hammerzeit http://lingualeo.com/ru

**Comment by halt-hammerzeit** [comment]
![](http://mtdata.ru/u24/photoF717/20260417436-0/original.png)

**Comment by gzigzigzeo** [comment]
@halt-hammerzeit 1) Так уж сложилось исторически 2) Я сторонник использования английского во всем что связано с программированием, все ж таки, программы мы пока не пишем на Е-Практикуме 3) Если хотите улучшить мир - сделайте PR - добавлю русское описание.

**Comment by halt-hammerzeit** [comment]
@gzigzigzeo Неудавшаяся попытка банальным способом переменить тему разговора. БИИИИП! Не засчитано.
Признайте свою ошибку, ибо она очевидна всем нормальным людям.

**Comment by halt-hammerzeit** [comment]
ЭТО ТАК ГЛУПО И СМЕШНО, КОГДА ВСЕ ПЫТАЮТСЯ КАЗАТЬСЯ МОДНЫМИ, СОВРЕМЕННЫМИ И ЗАПАДНЫМИ.
ХА ХА!
Я СМЕЮСЬ ТАКИМ ЛЮДЯМ ПРЯМО В ЛИЦО!
ХА ХА ХА ХА!

**Comment by halt-hammerzeit** [comment]
РОДНОГО ЯЗЫКА НЕ ЗНАЕТЕ И НЕ ЛЮБИТЕ.
ЧЕМОДАН, ВОКЗАЛ, ЕВРОПА!
ЧЕМОДАН, ВОКЗАЛ, ЕВРОПА!
ЧЕМОДАН, ВОКЗАЛ, ЕВРОПА!

**Comment by DarthSim** [comment]
Какого хрена название ИССУЕ для библиотеки для работы с РУССКИМИ адресами от РУССКОГО человека написано АНГЛИЙСКОМ языке?!..
ЧЕМОДАН, ВОКЗАЛ, ЕВРОПА!

**Comment by halt-hammerzeit** [comment]
ЗА СТАКАНЧИК КОФЕ ИЗ СТАРБАКСА И АЙФОН РОДИНУ ПРОДАЛИ!!!!111

**Comment by nepalez** [comment]
```
видъ РабБожий
  свойства_добавляемые_и_с_божией_помощью_удаляемые :имя, :адресъ_электронной_почты
конецъ

потехе_час = РабБожий.родить имя: 'потехе_час'
потехе_час.удалить_от_греха
```

**Comment by halt-hammerzeit** [comment]
Ничего смешного
https://github.com/halt-hammerzeit/sociopathy/blob/master/static%20resources/javascripts/%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D1%8C.js
Для вас понятие Родины ничего не значит.

**Comment by DarthSim** [comment]
Слишком толсто, уходи.

**Comment by yaroslav** [comment]
http://s1.webmshare.com/wNgmR.webm

**Comment by halt-hammerzeit** [comment]
@DarthSim НИЧЕГО ПОДОБНОГО!
Я ВАМ ЕЩЁ РАЗ ГОВОРЮ: КАКОГО !!! ДОКУМЕНТАЦИЯ К РУССКОЙ БИБЛИОТЕКЕ НАПИСАНА НА АНГЛИЙСКОМ ЯЗЫКЕ?!!!
ВЫ В СВОЁМ УМЕ ВООБЩЕ!!!!!!

**Comment by demiazz** [comment]
@halt-hammerzeit а ты никогда не думал, что эту русскую либу могут использовать в международной команде, например? Или вообще в зарубежной?

Ты когда нить видел open source, который китайцы фигачат? Вещи клевые, но фиг поймешь, как этим пользоваться - оно на китайском.

**Comment by halt-hammerzeit** [comment]
Так и вижу, хипстеры из Сан-Франциско спят и видят, как бы приделать себе КЛАДР или ФИАС в модный молодёжный стартап.
Вы нелогичны, и не пытайтесь это скрыть.
99.9999999% потенциальных интересующихся этой библиотекой - русскоговорящие.
ВЫ ДИСКРИМИНАТОРЫ, ТИРАНЫ И ТОТАЛИТАРИСТЫ!!
ЧЕЛОВЕК ИЗ ДЕРЕВНИ, ОН НЕ ХИПСТЕР, ОН НЕ ЗНАЕТ ВАШЕГО АНГЛИЙСКОГО ЯЗЫКА!!!!!!!!!!!!!!!!!!!!
ВЫ НЕ УВАЖАЕТЕ ДРУГИХ!

**Comment by nepalez** [comment]
@halt-hammerzeit  Николай, первое что тебе следовало бы сделать, так это сходить в ближайший хозяйственный магазин, купить там зубило, молоток, и выковырять с их и божьей помощью клавиши `Caps Lock` и `Shift` из имеющегося набора. Потом посредством оставшихся можно будет пообщаться за уважение.

**Comment by halt-hammerzeit** [comment]
Вы все только и умеете что уходить от ответа.
Правда глаза режет.
