### ISSUE TITLE
Memory limit problem

### ISSUE THREAD

**Issue by ex0rcist** [evilmartians/fias#14]
Faced an issue of "NoMemoryError" when running fias:import

> NoMemoryError: failed to allocate memory
/home/vagrant/.rvm/gems/ruby-2.2.1/gems/pg_data_encoder-0.1.10/lib/pg_data_encoder/encode_for_copy.rb:21:in `write'
/home/vagrant/.rvm/gems/ruby-2.2.1/gems/pg_data_encoder-0.1.10/lib/pg_data_encoder/encode_for_copy.rb:21:in `block in add'
/home/vagrant/.rvm/gems/ruby-2.2.1/gems/pg_data_encoder-0.1.10/lib/pg_data_encoder/encode_for_copy.rb:17:in `each'
/home/vagrant/.rvm/gems/ruby-2.2.1/gems/pg_data_encoder-0.1.10/lib/pg_data_encoder/encode_for_copy.rb:17:in `each_with_index'
/home/vagrant/.rvm/gems/ruby-2.2.1/gems/pg_data_encoder-0.1.10/lib/pg_data_encoder/encode_for_copy.rb:17:in `add'
/home/vagrant/.rvm/gems/ruby-2.2.1/gems/fias-1.0.2/lib/fias/import/copy.rb:18:in `block in encode'
/home/vagrant/.rvm/gems/ruby-2.2.1/gems/dbf-3.0.5/lib/dbf/table.rb:113:in `block in each'

By default it's writing DBF contents to StringIO, which size can't be more than 2**32 on 32-bit OS, so we are facing "Memory limit error" on https://github.com/pbrumm/pg_data_encoder/blob/master/lib/pg_data_encoder/encode_for_copy.rb#L21

Solved this by adding `use_tempfile: true` to https://github.com/evilmartians/fias/blob/master/lib/fias/import/copy.rb#L11

Another solution is to dump every, say, 1 mil of records from dbf to pg (we are facing problem at 1.4mil+)

**Comment by gzigzigzeo** [comment]
Well, I think, tempfile might slow import down. Batches may be better.

**Comment by ex0rcist** [comment]
Anyway, I've got memory limit error on step 3 (rebuild hierarchy), so installing x64 now :) At least we should warn users about that issues

**Comment by gzigzigzeo** [comment]
:-) Yeah, could you add warning to README. I will try to take a look on batching in this week.
